-- This script creates a database schema for an Oracle database.
-- It is designed to be run by the 'user' user, which is created by the
-- docker-compose setup with the password 'user_pass'.
-- Create the user
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = appuser;

-- Table: DEPARTMENTS
--
CREATE TABLE DEPARTMENTS (
    department_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR2(50) NOT NULL
);

--
-- Table: EMPLOYEES
--
CREATE TABLE EMPLOYEES (
    employee_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR2(50) NOT NULL,
    last_name     VARCHAR2(50) NOT NULL,
    email         VARCHAR2(100) NOT NULL,
    department_id NUMBER(10),
    CONSTRAINT fk_employees_departments FOREIGN KEY (department_id) REFERENCES DEPARTMENTS(department_id)
);

--
-- Table: SALARIES
--
CREATE TABLE SALARIES (
    salary_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER(10) NOT NULL,
    amount      NUMBER(10, 2) NOT NULL,
    from_date   DATE NOT NULL,
    to_date     DATE,
    CONSTRAINT fk_salaries_employees FOREIGN KEY (employee_id) REFERENCES EMPLOYEES(employee_id)
);

--
-- Table: AUDIT_LOG (Used by Trigger)
--
CREATE TABLE AUDIT_LOG (
    log_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name  VARCHAR2(30),
    action      VARCHAR2(10),
    action_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_name   VARCHAR2(30)
);

--
-- Indexes
--
CREATE INDEX idx_employees_last_name ON EMPLOYEES(last_name);
CREATE INDEX idx_salaries_employee_id ON SALARIES(employee_id);

--
-- VIEWS
--

-- View: Employee Directory with Department Names
CREATE OR REPLACE VIEW v_employee_details AS
SELECT e.employee_id, e.first_name, e.last_name, e.email, d.department_name
FROM EMPLOYEES e
LEFT JOIN DEPARTMENTS d ON e.department_id = d.department_id;

-- View: Current Salaries (Latest active salary)
CREATE OR REPLACE VIEW v_current_salaries AS
SELECT employee_id, amount, from_date
FROM SALARIES
WHERE to_date IS NULL OR to_date > SYSDATE;

--
-- FUNCTION
--

-- Function: Calculate Bonus (10% of salary)
CREATE OR REPLACE FUNCTION fn_calculate_bonus(p_employee_id IN NUMBER) 
RETURN NUMBER IS
    v_salary NUMBER;
BEGIN
    SELECT amount INTO v_salary 
    FROM v_current_salaries 
    WHERE employee_id = p_employee_id;
    
    RETURN v_salary * 0.10;
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN 0;
END;
/

--
-- PACKAGE (Specification & Body)
--

CREATE OR REPLACE PACKAGE emp_mgmt_pkg AS
    PROCEDURE add_employee(
        p_first_name IN VARCHAR2, 
        p_last_name IN VARCHAR2, 
        p_email IN VARCHAR2, 
        p_dept_id IN NUMBER
    );
END emp_mgmt_pkg;
/

CREATE OR REPLACE PACKAGE BODY emp_mgmt_pkg AS
    PROCEDURE add_employee(
        p_first_name IN VARCHAR2, 
        p_last_name IN VARCHAR2, 
        p_email IN VARCHAR2, 
        p_dept_id IN NUMBER
    ) IS
    BEGIN
        INSERT INTO EMPLOYEES (first_name, last_name, email, department_id)
        VALUES (p_first_name, p_last_name, p_email, p_dept_id);
    END add_employee;
END emp_mgmt_pkg;
/

--
-- PROCEDURE
--

CREATE OR REPLACE PROCEDURE sp_update_salary(
    p_emp_id IN NUMBER,
    p_new_amount IN NUMBER
) IS
BEGIN
    UPDATE SALARIES SET to_date = SYSDATE WHERE employee_id = p_emp_id AND to_date IS NULL;
    INSERT INTO SALARIES (employee_id, amount, from_date) VALUES (p_emp_id, p_new_amount, SYSDATE);
END;
/

--
-- TRIGGER
--

CREATE OR REPLACE TRIGGER trg_after_employee_insert
AFTER INSERT ON EMPLOYEES
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_LOG (table_name, action, user_name)
    VALUES ('EMPLOYEES', 'INSERT', USER);
END;
/

--
-- Add some sample data
--

-- Departments
INSERT INTO DEPARTMENTS (department_name) VALUES ('Human Resources');
INSERT INTO DEPARTMENTS (department_name) VALUES ('Engineering');
INSERT INTO DEPARTMENTS (department_name) VALUES ('Marketing');
INSERT INTO DEPARTMENTS (department_name) VALUES ('Sales');

-- Employees
INSERT INTO EMPLOYEES (first_name, last_name, email, department_id) VALUES ('John', 'Doe', 'john.doe@example.com', 2);
INSERT INTO EMPLOYEES (first_name, last_name, email, department_id) VALUES ('Jane', 'Smith', 'jane.smith@example.com', 2);
INSERT INTO EMPLOYEES (first_name, last_name, email, department_id) VALUES ('Peter', 'Jones', 'peter.jones@example.com', 3);

-- Salaries
INSERT INTO SALARIES (employee_id, amount, from_date, to_date) VALUES (1, 80000, TO_DATE('2023-01-01', 'YYYY-MM-DD'), NULL);
INSERT INTO SALARIES (employee_id, amount, from_date, to_date) VALUES (2, 85000, TO_DATE('2023-01-01', 'YYYY-MM-DD'), NULL);
INSERT INTO SALARIES (employee_id, amount, from_date, to_date) VALUES (3, 70000, TO_DATE('2023-01-01', 'YYYY-MM-DD'), NULL);

COMMIT;

