-- This script creates a database schema for an Oracle database.
-- It is designed to be run by the 'user' user, which is created by the
-- docker-compose setup with the password 'user_pass'.

--
-- Table: DEPARTMENTS
--
CREATE TABLE DEPARTMENTS (
    department_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR2(50) NOT NULL
);

--
-- Table: EMPLOYEES
--
CREATE TABLE EMPLOYEES (
    employee_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR2(50) NOT NULL,
    last_name     VARCHAR2(50) NOT NULL,
    email         VARCHAR2(100) NOT NULL,
    department_id NUMBER(10),
    CONSTRAINT fk_employees_departments FOREIGN KEY (department_id) REFERENCES DEPARTMENTS(department_id)
);

--
-- Table: SALARIES
--
CREATE TABLE SALARIES (
    salary_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER(10) NOT NULL,
    amount      NUMBER(10, 2) NOT NULL,
    from_date   DATE NOT NULL,
    to_date     DATE,
    CONSTRAINT fk_salaries_employees FOREIGN KEY (employee_id) REFERENCES EMPLOYEES(employee_id)
);

--
-- Indexes
--
CREATE INDEX idx_employees_last_name ON EMPLOYEES(last_name);
CREATE INDEX idx_salaries_employee_id ON SALARIES(employee_id);

--
-- Add some sample data
--

-- Departments
INSERT INTO DEPARTMENTS (department_name) VALUES ('Human Resources');
INSERT INTO DEPARTMENTS (department_name) VALUES ('Engineering');
INSERT INTO DEPARTMENTS (department_name) VALUES ('Sales');

-- Employees
INSERT INTO EMPLOYEES (first_name, last_name, email, department_id) VALUES ('John', 'Doe', 'john.doe@example.com', 2);
INSERT INTO EMPLOYEES (first_name, last_name, email, department_id) VALUES ('Jane', 'Smith', 'jane.smith@example.com', 2);
INSERT INTO EMPLOYEES (first_name, last_name, email, department_id) VALUES ('Peter', 'Jones', 'peter.jones@example.com', 3);

-- Salaries
INSERT INTO SALARIES (employee_id, amount, from_date, to_date) VALUES (1, 80000, TO_DATE('2023-01-01', 'YYYY-MM-DD'), NULL);
INSERT INTO SALARIES (employee_id, amount, from_date, to_date) VALUES (2, 85000, TO_DATE('2023-01-01', 'YYYY-MM-DD'), NULL);
INSERT INTO SALARIES (employee_id, amount, from_date, to_date) VALUES (3, 70000, TO_DATE('2023-01-01', 'YYYY-MM-DD'), NULL);

COMMIT;

